config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  root 'products#index'
  resource :basket
  resource :charge, only: %i(create)
  resources :products, only: %i(show) do
    scope module: :products do
      resources :add_to_baskets, only: %i(create)
      resources :delete_in_baskets, only: %i(create)
    end
  end

  namespace :admins do
    root to: "products#index"
    resources :products
    resources :messages
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  has_many :products, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/models/basket.rb
class Basket < ApplicationRecord
  has_many :basket_products, dependent: :destroy
  has_many :products, through: :basket_products

  def total_price(product_ids: nil)
    products = product_ids ? self.products.where(id: product_ids) : self.products
    products.sum(:price)
  end

end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  before_action :authenticate_user!
  def show
    basket = current_user.prepare_basket
    @products = basket.products
    @total_price = basket.total_price
  end
end

app/views/baskets/show.html.haml
.Cart
  .CartContainer
    %h3.CartMainTitle 買い物かごの中身
    .CartCollection
      - @products.each do |product|
        .CartBox
          .CartName
            .CartArtist
              #{product.artist}
            .CartTitle
              #{product.title}
          .CartPriceBox
            .CartPrice
              #{product.price}円
              = link_to product_delete_in_baskets_path(product), method: :post, data: {confirm: '削除してもいいですか？'} do
                %span.basket__delete
                  ✕
      .TotalPriceBox
        .TotalPrice
          .a 合計金額
          .i #{@total_price} 
          .yen 円
    .ChargesBox
      = form_tag charge_path do
        - @products.each do |p|
          = hidden_field_tag 'product_ids[]', p.id
        %script.stripe-button{"src": "https://checkout.stripe.com/checkout.js", "data": { "key": ENV['STRIPE_PUBLISHABLE_KEY'], "description": "payment", "amount": @total_price, "locale": "auto", "currency": "jpy"}}
    .BackLinkBox
      = link_to 'トップへ戻る', root_path, class: "BackLink"