config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  root 'products#index'
  resource :basket
  resource :charge, only: %i(create)
  resources :products, only: %i(show) do
    scope module: :products do
      resources :add_to_baskets, only: %i(create)
      resources :delete_in_baskets, only: %i(create)
    end
  end

  namespace :admins do
    root to: "products#index"
    resources :products
    resources :messages
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :images, presence: true
  validates :title,
            :artist,
            :label,
            :year,
            :format,
            :made_in,
            :vinyl,
            :jacket,
            :price,
            :comment_track_list,
            presence: true

  has_many :images, dependent: :destroy
  has_many :basket_products, dependent: :destroy
  has_many :purchase_product_records, dependent: :destroy
  belongs_to :admin

  accepts_nested_attributes_for :images, allow_destroy: true


end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < Admins::ApplicationController

  before_action :show_all_instance, only: [ :edit, :show, :destroy]

  def index
    @messages = Message.all.order('created_at DESC').first(3)
    @products = Product.all
  end

  def new
    @product = current_admin.products.build
    @product.images.new
  end

  def create
    @product = current_admin.products.build(product_params)
    if @product.save
      redirect_to admins_root_path
      flash[:notice] = '出品が完了しました！'
    else
      flash[:alert] = '必須項目を入力してください'
      render :new
    end
  end

  def edit
  end

  def update
    @product = Product.find(params[:id])
    if product_params[:images_attributes].nil?
      flash[:alert] = '画像を１枚以上入れてください'
      redirect_to edit_admins_product_path
    else
      exit_ids = []
      product_params[:images_attributes].each do |a,b|
        exit_ids << product_params[:images_attributes].dig(:"#{a}",:id).to_i
      end
      ids = Image.where(product_id: params[:id]).map{|image| image.id }
      delete__db = ids - exit_ids
      Image.where(id:delete__db).destroy_all
      if @product.update(product_params)
         redirect_to root_path
      else
        flash[:alert] = '更新できませんでした'
        render :edit
      end
    end
  end


  private

  def product_params
    params.require(:product).permit(:artist, :title, :year, :format, :made_in, :vinyl, :jacket, :price, :comment_track_list, :label, images_attributes: [:image, :_destroy, :id]).merge(admin_id: current_admin.id)
  end

  def show_all_instance
    @product = Product.find(params[:id])
    @images = Image.where(product_id: params[:id])
    @images_first = Image.where(product_id: params[:id]).first
  end

end

app/controllers/products/add_to_baskets_controller.rb
class Products::AddToBasketsController < Products::ApplicationController
  def create
    basket = current_user.prepare_basket
    product = Product.find(params[:product_id])
    basket.basket_products.create!(product_id: product.id) 
    redirect_to basket_path
  end
end

app/controllers/products/application_controller.rb
class Products::ApplicationController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/products/delete_in_baskets_controller.rb
class Products::DeleteInBasketsController < Products::ApplicationController
  def create
    basket = current_user.prepare_basket
    product = Product.find(params[:product_id])
    
    basket_product = basket.basket_products.find_by(product_id: product.id)
    basket_product.destroy!
    
    redirect_to basket_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :show_all_instance, only: [ :edit, :show, :destroy]

  def index
    @products = Product.all.order('created_at DESC').first(5)
    @messages = Message.all.order('created_at DESC').first(3)
  end

  def show
    @product = Product.find(params[:id])
    @products = Product.includes(:images)
  end

  private

  def show_all_instance
    @images = Image.where(product_id: params[:id])
    @images_first = Image.where(product_id: params[:id]).first
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admins/products/_admin_header.html.haml
.AdminHeader
  .TopLink
    - if current_user.present?
      = link_to 'FukinotoRecords', root_path
    - elsif current_admin.present?
      = link_to 'FukinotoAdmin', admins_root_path
    - else
      = link_to 'FukinotoRecords', root_path
  .HeaderMenu
    .HeaderSession
      = link_to 'ユーザー画面へ', root_path, class: "HeaderLogOut"
      = link_to '管理者ログアウト', destroy_admin_session_path, method: :delete, class: "HeaderLogOut"

app/views/admins/products/_admin_products.html.haml
.NewArrival
  .News
    .NewTitle 新着情報一覧
    .NewsBox
      - @messages.each do |message|
        .NewsContent
          = message.created_at.strftime('%Y/%m/%d')
          = message.content
  .NewArrivalList
    .NewTitle 商品一覧
    .ProductIndexBox
      - @products.each do |product|
        = link_to product_path(product.id) do
          .Product
            = image_tag product.images.first.image_url, class: 'list_image', width: 150, height: 150
            .artist
              = product.artist
            .title
              = product.title
            .price
              = product.price.to_s(:delimited)
              円

app/views/admins/products/_admin_side_bar.html.haml
.SideBar
  .Category 管理者機能
  %ul
    %li
      = link_to '新着情報通知', new_admins_message_path, class: 'SideBarGenre'
    %li
      = link_to '商品登録', new_admins_product_path, class: 'SideBarGenre'
  .Category 商品カテゴリ
  %ul
    %li
      = link_to '新着商品', '#', class: 'SideBarGenre'
    %li
      = link_to 'ジャズ', '#', class: 'SideBarGenre'
    %li
      = link_to 'ファンク', '#', class: 'SideBarGenre'
    %li
      = link_to 'ソウル', '#', class: 'SideBarGenre'
    %li
      = link_to 'ディスコ', '#', class: 'SideBarGenre'
    %li
      = link_to 'ハウス', '#', class: 'SideBarGenre'
    %li
      = link_to 'ヒップホップ', '#', class: 'SideBarGenre'
    %li
      = link_to 'その他', '#', class: 'SideBarGenre'

app/views/admins/products/edit.html.haml
.NewFormWrapper
  .NewFormBox
    = form_with model: [:admins, @product], local: true, class: "ProductForm" do |f|
      #image-box-1{class:"#{@images.last.id}"}
        - @images.each do |img|
          .item-image{id:img.id}
            = image_tag(img.image.url)
            .item-image__operetion
              .item-image__operetion--edit__delete__hidden 削除
        %label.img-label{for: "img-file"}
          = icon('fas', 'camera', class: 'UploadCamera')
          .displayhide
            #image-box__container{class:"item-num-#{@images.length}"}
              #append-js-edit
                = f.fields_for :images do |image|
                  .js-file_group{"data-index" => "#{image.index}"}
                    = image.file_field :image, type: 'file', value:"#{image.object.id}",style: "",  id:"img-file", class:'js-file-edit',name: "product[images_attributes][#{@product.images.count}][image]", data:{index:""}
      .InputBox
        .NewLabelBox
          %span アーティスト
        .FormField
          = f.text_field :artist, class: "NewProductForm"
        .NewLabelBox
          %span タイトル
        .FormField
          = f.text_field :title, class: "NewProductForm"
        .NewLabelBox
          %span レーベル
        .FormField
          = f.text_field :label, class: "NewProductForm"
        .NewLabelBox
          %span 発行年
        .FormField
          = f.number_field :year, class: "NewProductForm"
        .NewLabelBox
          %span フォーマット
        .FormField
          = f.text_field :format, class: "NewProductForm"
        .NewLabelBox
          %span 製造国
        .FormField
          = f.text_field :made_in, class: "NewProductForm"
        .NewLabelBox
          %span レコードコンディション
        .FormField
          = f.text_field :vinyl, class: "NewProductForm"
        .NewLabelBox
          %span ジャケットコンディション
        .FormField
          = f.text_field :jacket, class: "NewProductForm"
        .NewLabelBox
          %span 価格（税込）
        .FormField
          = f.number_field :price, class: "NewProductForm"
        .NewLabelBox
          %span コメント、トラックリスト
        .FormField
          = f.text_area :comment_track_list, class: "NewProductText"
        .FormBtn
          = f.submit class: "NewProductSubmit"

app/views/admins/products/index.html.haml
.wrapper
  = render 'admin_header'
  .main
    = render "admin_side_bar"
    = render "admin_products"

app/views/admins/products/new.html.haml
.NewFormWrapper
  = render 'admin_header'
  .NewFormBox
    = form_with model: [:admins, @product], local: true, class: "ProductForm" do |f|
      .imageUpload
        .prev-content
        .label-content
          %label{for: "product_images_attributes_0_image", class: "label-box"}
            %pre.label-box__text-visible クリックしてファイルをアップロード
        .hidden-content
          = f.fields_for :images do |i|
            = i.file_field :image, class:"hidden-field"
            %input{class:"hidden-field", type: "file", name: "product[images_attributes][1][image]", id: "product_images_attributes_1_image" }
            %input{class:"hidden-field", type: "file", name: "product[images_attributes][2][image]", id: "product_images_attributes_2_image" }
            %input{class:"hidden-field", type: "file", name: "product[images_attributes][3][image]", id: "product_images_attributes_3_image" }
            %input{class:"hidden-field", type: "file", name: "product[images_attributes][4][image]", id: "product_images_attributes_4_image" }
      .InputBox
        .NewLabelBox
          %span アーティスト
        .FormField
          = f.text_field :artist, class: "NewProductForm"
        .NewLabelBox
          %span タイトル
        .FormField
          = f.text_field :title, class: "NewProductForm"
        .NewLabelBox
          %span レーベル
        .FormField
          = f.text_field :label, class: "NewProductForm"
        .NewLabelBox
          %span 発行年
        .FormField
          = f.number_field :year, class: "NewProductForm"
        .NewLabelBox
          %span フォーマット
        .FormField
          = f.text_field :format, class: "NewProductForm"
        .NewLabelBox
          %span 製造国
        .FormField
          = f.text_field :made_in, class: "NewProductForm"
        .NewLabelBox
          %span レコードコンディション
        .FormField
          = f.text_field :vinyl, class: "NewProductForm"
        .NewLabelBox
          %span ジャケットコンディション
        .FormField
          = f.text_field :jacket, class: "NewProductForm"
        .NewLabelBox
          %span 価格（税込）
        .FormField
          = f.number_field :price, class: "NewProductForm"
        .NewLabelBox
          %span コメント、トラックリスト
        .FormField
          = f.text_area :comment_track_list, class: "NewProductText"
        .FormBtn
          = f.submit class: "NewProductSubmit"