config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  root 'products#index'
  resource :basket
  resource :charge, only: %i(create)
  resources :products, only: %i(show) do
    scope module: :products do
      resources :add_to_baskets, only: %i(create)
      resources :delete_in_baskets, only: %i(create)
    end
  end

  namespace :admins do
    root to: "products#index"
    resources :products
    resources :messages
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :images, presence: true
  validates :title,
            :artist,
            :label,
            :year,
            :format,
            :made_in,
            :vinyl,
            :jacket,
            :price,
            :comment_track_list,
            presence: true

  has_many :images, dependent: :destroy
  has_many :basket_products, dependent: :destroy
  has_many :purchase_product_records, dependent: :destroy
  belongs_to :admin

  accepts_nested_attributes_for :images, allow_destroy: true


end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < Admins::ApplicationController

  before_action :show_all_instance, only: [ :edit, :show, :destroy]

  def index
    @messages = Message.all.order('created_at DESC').first(3)
    @products = Product.all
  end

  def new
    @product = current_admin.products.build
    @product.images.new
  end

  def create
    @product = current_admin.products.build(product_params)
    if @product.save
      redirect_to admins_root_path
      flash[:notice] = '出品が完了しました！'
    else
      flash[:alert] = '必須項目を入力してください'
      render :new
    end
  end

  def edit
  end

  def update
    @product = Product.find(params[:id])
    if product_params[:images_attributes].nil?
      flash[:alert] = '画像を１枚以上入れてください'
      redirect_to edit_admins_product_path
    else
      exit_ids = []
      product_params[:images_attributes].each do |a,b|
        exit_ids << product_params[:images_attributes].dig(:"#{a}",:id).to_i
      end
      ids = Image.where(product_id: params[:id]).map{|image| image.id }
      delete__db = ids - exit_ids
      Image.where(id:delete__db).destroy_all
      if @product.update(product_params)
         redirect_to root_path
      else
        flash[:alert] = '更新できませんでした'
        render :edit
      end
    end
  end


  private

  def product_params
    params.require(:product).permit(:artist, :title, :year, :format, :made_in, :vinyl, :jacket, :price, :comment_track_list, :label, images_attributes: [:image, :_destroy, :id]).merge(admin_id: current_admin.id)
  end

  def show_all_instance
    @product = Product.find(params[:id])
    @images = Image.where(product_id: params[:id])
    @images_first = Image.where(product_id: params[:id]).first
  end

end

app/controllers/products/add_to_baskets_controller.rb
class Products::AddToBasketsController < Products::ApplicationController
  def create
    basket = current_user.prepare_basket
    product = Product.find(params[:product_id])
    basket.basket_products.create!(product_id: product.id) 
    redirect_to basket_path
  end
end

app/controllers/products/application_controller.rb
class Products::ApplicationController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/products/delete_in_baskets_controller.rb
class Products::DeleteInBasketsController < Products::ApplicationController
  def create
    basket = current_user.prepare_basket
    product = Product.find(params[:product_id])
    
    basket_product = basket.basket_products.find_by(product_id: product.id)
    basket_product.destroy!
    
    redirect_to basket_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :show_all_instance, only: [ :edit, :show, :destroy]

  def index
    @products = Product.all.order('created_at DESC').first(5)
    @messages = Message.all.order('created_at DESC').first(3)
  end

  def show
    @product = Product.find(params[:id])
    @products = Product.includes(:images)
  end

  private

  def show_all_instance
    @images = Image.where(product_id: params[:id])
    @images_first = Image.where(product_id: params[:id]).first
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_footer.html.haml
.Footer

app/views/products/_header.html.haml
.Header
  .TopLink
    - if current_user.present?
      = link_to 'FukinotoRecords', root_path
    - elsif current_admin.present?
      = link_to 'FukinotoAdmin', admins_root_path
    - else
      = link_to 'FukinotoRecords', root_path
  .HeaderMenu
    .HeaderCart
      - if current_user.present?
        = link_to basket_path do
          = icon('fa', 'shopping-cart')
          Cart
      - elsif current_admin.present?
        = link_to '管理者用ページ', admins_root_path
      - else
        = link_to '新規会員登録',new_user_registration_path
    .HeaderSession
      - if current_user.present?
        = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "HeaderLogOut"
      - elsif current_admin.present?
        = link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: "HeaderLogOut"
      - else
        = link_to "ユーザーログイン", new_user_session_path
        = link_to "管理者ログイン", new_admin_session_path

app/views/products/_product.html.haml
.ShowProduct
  .Image-Price-Box
    .photo__box
      %ul.photo__innner
        %li
          = image_tag @product.images.first.image.url, class: "main__image"
          %ul.ImageFlame
            - @product.images.each do |image|
              %li
                = image_tag image.image.url, class: "image__list"
    .ShoppingBox
      .ArtistTitleBox
        Artist
        .ArtistLabel
          = @product.artist
        Title
        .TitleLabel
          = @product.title
      .PriceBox
        .PriceLabel PRICE :
        .Price
          = @product.price.to_s(:delimited)
          円
        .WithTax
          (税込)
      -if admin_signed_in? && current_admin.id == @product.admin_id
        .CartBtn
          = link_to "編集", edit_admins_product_path, class: "CartBtnLink"
      -else
        .CartBtn
          = link_to "カートに入れる", product_add_to_baskets_path(@product), class: "CartBtnLink", method: :post
      .AuditionBox
        試聴はここをクリック(未実装)
  .ProductBox
    .InfoBox
      .category
        .label GENRE :
      .category
        .label LABEL :
        = @product.label
      .category
        .label YEAR :
        = @product.year
      .category
        .label FORMAT :
        = @product.format
      .category
        .label MADE IN :
        = @product.made_in
    .ConditionBox
      .Condition CONDITION
      .category
        .conditionlabel VINYL :
        = @product.vinyl
      .category
        .conditionlabel COVER :
        = @product.jacket
  .comment
    .label COMMENT & TRACK LIST
    = @product.comment_track_list

app/views/products/_product_index.html.haml
.NewArrival
  .News
    .NewTitle What's News
    .NewsBox
      - @messages.each do |message|
        .NewsContent
          = message.created_at.strftime('%Y/%m/%d')
          = message.content
  .NewArrivalList
    .NewTitle New Arrival
    .ProductIndexBox
      - @products.each do |product|
        = link_to product_path(product.id) do
          .Product
            = image_tag product.images.first.image_url, class: 'list_image', width: 150, height: 150
            .artist
              = product.artist
            .title
              = product.title
            .price
              = product.price.to_s(:delimited)
              円

app/views/products/_side_bar.html.haml
.SideBar
  .Category Category
  %ul
    %li
      = link_to 'NEW ARRIVAL', '#', class: 'SideBarGenre'
    %li
      = link_to 'JAZZ', '#', class: 'SideBarGenre'
    %li
      = link_to 'FUNK', '#', class: 'SideBarGenre'
    %li
      = link_to 'SOUL', '#', class: 'SideBarGenre'
    %li
      = link_to 'DISCO', '#', class: 'SideBarGenre'
    %li
      = link_to 'HOUSE', '#', class: 'SideBarGenre'
    %li
      = link_to 'HIPHOP', '#', class: 'SideBarGenre'
    %li
      = link_to 'OTHER', '#', class: 'SideBarGenre'

app/views/products/index.html.haml
.wrapper
  = render "header"
  .main
    = render "side_bar"
    = render "product_index"
  .SubSideBar
  = render "footer"

app/views/products/new.html.haml
%h1 商品登録
.container
  = form_with model: @product, local: true do |f|
    .imageUpload
      .prev-content
      .label-content
        %label{for: "product_images_attributes_0_image", class: "label-box"}
          %pre.label-box__text-visible クリックしてファイルをアップロード
      .hidden-content
        = f.fields_for :images do |i|
          = i.file_field :image, class:"hidden-field"
          %input{class:"hidden-field", type: "file", name: "product[images_attributes][1][image]", id: "product_images_attributes_1_image" }
          %input{class:"hidden-field", type: "file", name: "product[images_attributes][2][image]", id: "product_images_attributes_2_image" }
          %input{class:"hidden-field", type: "file", name: "product[images_attributes][3][image]", id: "product_images_attributes_3_image" }
          %input{class:"hidden-field", type: "file", name: "product[images_attributes][4][image]", id: "product_images_attributes_4_image" }
    .FormField
      .FormField__label--normal
        %label アーティスト
      .form_field__input
        = f.text_field :artist
    .FormField
      .FormField__label--normal
        = f.label :タイトル
      .form_field__input
        = f.text_field :title
    .FormField
      .FormField__label--normal
        = f.label :レーベル
      .form_field__input
        = f.text_field :label
    .FormField
      .FormField__label--normal
        = f.label :発行年
      .form_field__input
        = f.text_field :year
    .FormField
      .FormField__label--normal
        = f.label :フォーマット
      .form_field__input
        = f.text_field :format
    .FormField
      .FormField__label--normal
        = f.label :製造国
      .form_field__input
        = f.text_field :made_in
    .FormField
      .FormField__label--normal
        = f.label :レコードコンディション
      .form_field__input
        = f.text_field :vinyl
    .FormField
      .FormField__label--normal
        = f.label :ジャケットコンディション
      .form_field__input
        = f.text_field :jacket
    .FormField
      .FormField__label--normal
        = f.label :価格（税込）
      .form_field__input
        = f.text_field :price
    .FormField
      .FormField__label--normal
        = f.label :コメント、トラックリスト
      .form_field__input
        = f.text_area :comment_track_list
    .actions
      = f.submit
  = link_to '一覧に戻る', products_path

app/views/products/show.html.haml
.wrapper
  = render "header"
  .main
    = render "side_bar"
    = render "product"
  = render "footer"